apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: traefik-default
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-25.0.0
  name: traefik
  namespace: default
